### ISSUE TITLE
Not able to find a download for pdfresurrect

### ISSUE THREAD

**Issue by Hiteshsaai** [enferex/pdfresurrect#12]
I want to use pdfresurrect, but i am not getting any proper link to download, can you help me get that downloaded.

**Comment by enferex** [comment]
Hi @Hiteshsaai, I do not provide any built versions of pdfresurrect.  However, you might be able to find a version specific to your platform, via a package manager.  For instance `apt-get install pdfresurrect`

**Comment by Hiteshsaai** [comment]
got it @enferex  thanks 👍
